export const Services = [
  {
    "id": 1,
    "category": "Automotive Services", 
    "src": "/service/vshas.jpg",
    "services": [
      {
        "id": 1,
        "name": "Auto Spray Painting",
        "src": "/service/auto_spray.jpg",
        "link": "",
      },
      {
        "id": 2,
        "name": "Car AC Repair & Maintenance",
        "src": "/service/car_ac.jpg",
        "link": "",
      },
      {
        "id": 3,
        "name": "Mechanical Repairs",
        "src": "/service/mechanic.jpg",
        "link": "",
      },
      {
        "id": 4,
        "name": "Panel Beating & Bodywork",
        "src": "/service/panel_beater.jpg",
        "link": "",
      },
      {
        "id": 5,
        "name": "Electrical Rewiring",
        "src": "/service/re-wire.jpg",
        "link": "",
      },
      {
        "id": 6,
        "name": "Towing Services",
        "src": "/service/towing.jpg",
        "link": "",
      },
      {
        "id": 7,
        "name": "Tire Repair & Vulcanization",
        "src": "/service/vulcanizers.jpg",
        "link": "",
      },
      {
        "id": 8,
        "name": "Wheel Balancing & Alignment",
        "src": "/service/wheel balance.jpg",
        "link": "",
      },
    ],
  },
  {
    "id": 2,
    "category": "Maintenance Repair, Construction & Fabrication Services", 
    "src": "/service/vshm3.jpg",
    "services": [
      {
        "id": 1,
        "name": "AC, Fridge & Cooker Repair",
        "src": "/service/Ac, fridge and cooker.jpg",
        "link": "",
      },
      {
        "id": 2,
        "name": "Carpentry Services",
        "src": "/service/carpenters.jpg",
        "link": "",
      },
      {
        "id": 3,
        "name": "Computer Repair & Maintenance",
        "src": "/service/computer.jpg",
        "link": "",
      },
      {
        "id": 4,
        "name": "Dish Installation & Repair",
        "src": "/service/satelite.jpg",
        "link": "",
      },
      {
        "id": 5,
        "name": "Electrical Services",
        "src": "/service/electrician.jpg",
        "link": "",
      },
      {
        "id": 6,
        "name": "Fumigation & Pest Control",
        "src": "/service/fumigator.jpg",
        "link": "",
      },
      {
        "id": 7,
        "name": "Gardening & Landscaping",
        "src": "/service/gardeners.jpg",
        "link": "",
      },
      {
        "id": 8,
        "name": "Generator Servicing & Repair",
        "src": "/service/gen.jpg",
        "link": "",
      },
      {
        "id": 9,
        "name": "Masonry & Construction",
        "src": "/service/masonry.jpg",
        "link": "",
      },
      {
        "id": 10,
        "name": "Painting & Decorating",
        "src": "/service/painters.jpg",
        "link": "",
      },
      {
        "id": 11,
        "name": "Phone Repair & Maintenance",
        "src": "/service/mobile_repair.jpg",
        "link": "",
      },
      {
        "id": 12,
        "name": "Plumbing Services",
        "src": "/service/plumbing.jpg",
        "link": "",
      },
      {
        "id": 13,
        "name": "Recycling ( Trash for Cash )",
        "src": "/service/rycyclers.jpg",
        "link": "",
      },
      {
        "id": 14,
        "name": "Shoe Repair & Maintenance",
        "src": "/service/shoe_repair.jpg",
        "link": "",
      },
      {
        "id": 15,
        "name": "Solar Panel Installation & Maintenance",
        "src": "/service/solar.jpg",
        "link": "",
      },
      {
        "id": 16,
        "name": "Tiling & Flooring",
        "src": "/service/tiling.jpg",
        "link": "",
      },
      {
        "id": 17,
        "name": "Welding & Fabrication",
        "src": "/service/welding.jpg",
        "link": "",
      },
    ],
  },
  {
    "id": 3,
    "category": "Lifestyle & Other Personal Services", 
    "src": "/service/vshos.jpg",
    "services": [
      {
        "id": 1,
        "name": "Architectural Design & Consulting",
        "src": "/service/architecture.jpg",
        "link": "",
      },
      {
        "id": 2,
        "name": "Barbing",
        "src": "/service/barbing.jpg",
        "link": "",
      },
      {
        "id": 3,
        "name": "BBQ  Services",
        "src": "/service/bbq.jpg",
        "link": "",
      },
      {
        "id": 4,
        "name": "Camera & Photography Services",
        "src": "/service/camera.jpg",
        "link": "",
      },
      {
        "id": 5,
        "name": "Car Washing & Detailing",
        "src": "/service/car_wash.jpg",
        "link": "",
      },
      {
        "id": 6,
        "name": "Catering & Event Services",
        "src": "/service/catering.jpg",
        "link": "",
      },
      {
        "id": 7,
        "name": "Delivery & Logistics",
        "src": "/service/logistic.jpg",
        "link": "",
      },
      {
        "id": 8,
        "name": "Event Planning & Rentals",
        "src": "/service/event.jpg",
        "link": "",
      },
      {
        "id": 9,
        "name": "FMCG Procurement & Logistics",
        "src": "/service/fmcg.jpg",
        "link": "",
      },
      {
        "id": 10,
        "name": "Gas Delivery & Refill",
        "src": "/service/gas.jpg",
        "link": "",
      },
      {
        "id": 11,
        "name": "Islamiya & Quranic Studies",
        "src": "/service/islamiya.jpg",
        "link": "",
      },
      {
        "id": 12,
        "name": "Home Tuition & Lessons",
        "src": "/service/Home_lesson.jpg",
        "link": "",
      },
      {
        "id": 13,
        "name": "Laundry & Dry Cleaning",
        "src": "/service/laundry.jpg",
        "link": "",
      },
      {
        "id": 14,
        "name": "Medical & Healthcare",
        "src": "/service/phamarcist.jpg",
        "link": "",
      },
      {
        "id": 15,
        "name": "Domestic Help & Cleaning",
        "src": "/service/maid.jpg",
        "link": "",
      },
      {
        "id": 16,
        "name": "Manicure & Pedicure",
        "src": "/service/manicure.jpg",
        "link": "",
      },
      {
        "id": 17,
        "name": "Real Estate & Property Services",
        "src": "/service/agents.jpg",
        "link": "",
      },
      {
        "id": 18,
        "name": "Security Services",
        "src": "/service/security.jpg",
        "link": "",
      },
      {
        "id": 19,
        "name": "Tailoring Services",
        "src": "/service/tailor.jpg",
        "link": "",
      },
    ],
  },
];
