export const ServiceList = [


  {
    "id": 1,
    "name": "Auto Spray Painting",
    "src": "/service/auto_spray.jpg",
    "link": "",
  },
  {
    "id": 2,
    "name": "Car AC Repair & Maintenance",
    "src": "/service/car_ac.jpg",
    "link": "",
  },
  {
    "id": 3,
    "name": "Mechanical Repairs",
    "src": "/service/mechanic.jpg",
    "link": "",
  },
  {
    "id": 4,
    "name": "Panel Beating & Bodywork",
    "src": "/service/panel_beater.jpg",
    "link": "",
  },
  {
    "id": 5,
    "name": "Electrical Rewiring",
    "src": "/service/re-wire.jpg",
    "link": "",
  },
  {
    "id": 6,
    "name": "Towing Services",
    "src": "/service/towing.jpg",
    "link": "",
  },
  {
    "id": 7,
    "name": "Tire Repair & Vulcanization",
    "src": "/service/vulcanizers.jpg",
    "link": "",
  },
  {
    "id": 8,
    "name": "Wheel Balancing & Alignment",
    "src": "/service/wheel balance.jpg",
    "link": "",
  },
  
  {
    "id": 9,
    "name": "AC, Fridge & Cooker Repair",
    "src": "/service/Ac, fridge and cooker.jpg",
    "link": "",
  },
  {
    "id": 10,
    "name": "Carpentry Services",
    "src": "/service/carpenters.jpg",
    "link": "",
  },
  {
    "id": 11,
    "name": "Computer Repair & Maintenance",
    "src": "/service/computer.jpg",
    "link": "",
  },
  {
    "id": 12,
    "name": "Dish Installation & Repair",
    "src": "/service/satelite.jpg",
    "link": "",
  },
  {
    "id": 13,
    "name": "Electrical Services",
    "src": "/service/electrician.jpg",
    "link": "",
  },
  {
    "id": 14,
    "name": "Fumigation & Pest Control",
    "src": "/service/fumigator.jpg",
    "link": "",
  },
  {
    "id": 15,
    "name": "Gardening & Landscaping",
    "src": "/service/gardeners.jpg",
    "link": "",
  },
  {
    "id": 16,
    "name": "Generator Servicing & Repair",
    "src": "/service/gen.jpg",
    "link": "",
  },
  {
    "id":17,
    "name": "InterLocking Floors",
    "src": "/service/interLock.jpg",
    "link": "",
  },
  {
    "id": 18,
    "name": "Masonry & Construction",
    "src": "/service/masonry.jpg",
    "link": "",
  },
  {
    "id": 19,
    "name": "Painting",
    "src": "/service/painters.jpg",
    "link": "",
  },
  {
    "id": 20,
    "name": "Phone Repair & Maintenance",
    "src": "/service/mobile_repair.jpg",
    "link": "",
  },
  {
    "id": 21,
    "name": "Plumbing Services",
    "src": "/service/plumbing.jpg",
    "link": "",
  },
  {
    "id": 22,
    "name": "P.O.P",
    "src": "/service/pop.jpg",
    "link": "",
  },
  {
    "id": 23,
    "name": "Recycling ( Trash for Cash )",
    "src": "/service/rycyclers.jpg",
    "link": "",
  },
  {
    "id": 24,
    "name": "Shoe Repair & Maintenance",
    "src": "/service/shoe_repair.jpg",
    "link": "",
  },
  {
    "id": 25,
    "name": "Solar Panel Installation & Maintenance",
    "src": "/service/solar.jpg",
    "link": "",
  },
  {
    "id": 26,
    "name": "Tiling & Flooring",
    "src": "/service/tiling.jpg",
    "link": "",
  },
  {
    "id": 27,
    "name": "Welding & Fabrication",
    "src": "/service/welding.jpg",
    "link": "",
  },
  {
    "id": 28,
    "name": "Architectural Design & Consulting",
    "src": "/service/architecture.jpg",
    "link": "",
  },
  {
    "id": 29,
    "name": "Barbing",
    "src": "/service/barbing.jpg",
    "link": "",
  },
  {
    "id": 30,
    "name": "BBQ  Services",
    "src": "/service/bbq.jpg",
    "link": "",
  },
  {
    "id": 31,
    "name": "Camera & Photography Services",
    "src": "/service/camera.jpg",
    "link": "",
  },
  {
    "id": 32,
    "name": "Cap Wash and Maintenance",
    "src": "/service/cap.jpg",
    "link": "",
  },
  {
    "id": 33,
    "name": "Car Washing & Detailing",
    "src": "/service/car_wash.jpg",
    "link": "",
  },
  {
    "id": 34,
    "name": "Catering & Event Services",
    "src": "/service/catering.jpg",
    "link": "",
  },
  {
    "id": 35,
    "name": "Delivery & Logistics",
    "src": "/service/logistic.jpg",
    "link": "",
  },
  {
    "id": 36,
    "name": "Event Planning & Rentals",
    "src": "/service/event.jpg",
    "link": "",
  },
  {
    "id": 37,
    "name": "FMCG Procurement & Logistics",
    "src": "/service/fmcg.jpg",
    "link": "",
  },
  {
    "id": 38,
    "name": "Gas Delivery & Refill",
    "src": "/service/gas.jpg",
    "link": "",
  },
  {
    "id": 39,
    "name": "Islamiya & Quranic Studies",
    "src": "/service/islamiya.jpg",
    "link": "",
  },
  {
    "id": 40,
    "name": "Home Tuition & Lessons",
    "src": "/service/Home_lesson.jpg",
    "link": "",
  },
  {
    "id": 41,
    "name": "Laundry & Dry Cleaning",
    "src": "/service/laundry.jpg",
    "link": "",
  },
  {
    "id": 42,
    "name": "Medical & Healthcare",
    "src": "/service/phamarcist.jpg",
    "link": "",
  },
  {
    "id": 43,
    "name": "Domestic Help & Cleaning",
    "src": "/service/maid.jpg",
    "link": "",
  },
  {
    "id": 44,
    "name": "Manicure & Pedicure",
    "src": "/service/manicure.jpg",
    "link": "",
  },
  {
    "id": 45,
    "name": "Real Estate & Property Services",
    "src": "/service/agents.jpg",
    "link": "",
  },
  {
    "id": 46,
    "name": "Security Services",
    "src": "/service/security.jpg",
    "link": "",
  },
  {
    "id": 47,
    "name": "Tailoring Services",
    "src": "/service/tailor.jpg",
    "link": "",
  },

 
];
